### ISSUE TITLE
iptables: No chain/target/match by that name.

### ISSUE THREAD

**Issue by fokytoq** [nofee-ng/nofee-ng#12]
After confirming "Found NoFee Wallet:", error "iptables: No chain/target/match by that name".
EthOS 1.3.3, standalone mode nofee-ng

**Comment by nofee-ng** [comment]
Thank you for reporting that bug, I'm working on it

**Comment by fokytoq** [comment]
I tried running Nofee-ng on Ubuntu 20.4.2. Everything works.
I don't understand why EthOS shows an error, because EthOS is created from Ubuntu.

**Comment by nofee-ng** [comment]
Where can I download EthOS and test it. It seems I have to buy it. And it's rather old (EthOS 1.3.3 was released on October 9 2018)

**Comment by fokytoq** [comment]
The system is not supported and you will not be able to buy it. I can throw off the ethos img file or show you the installed modules and kernel functions.
4.15.12 kernel
Which modules should be active for your script?

**Comment by nofee-ng** [comment]
We use tproxy.

**Comment by nofee-ng** [comment]
We use tproxy.
