### ISSUE TITLE
unable to resolve domain names after running 'nofee_eth -rs' 

### ISSUE THREAD

**Issue by zenbooster** [nofee-ng/nofee-ng#15]
Hello!

```
zenbooster@zenfarm0:~$ sudo cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
...
```
```
zenbooster@zenfarm0:~$ iptables --version
iptables v1.8.4 (legacy)
```
```
zenbooster@zenfarm0:~$ nslookup google.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   google.com
Address: 64.233.161.139
Name:   google.com
Address: 64.233.161.102
Name:   google.com
Address: 64.233.161.113
Name:   google.com
Address: 64.233.161.100
Name:   google.com
Address: 64.233.161.101
Name:   google.com
Address: 64.233.161.138
Name:   google.com
Address: 2a00:1450:4010:c01::66
Name:   google.com
Address: 2a00:1450:4010:c01::8b
Name:   google.com
Address: 2a00:1450:4010:c01::65
Name:   google.com
Address: 2a00:1450:4010:c01::71
```
```
zenbooster@zenfarm0:~$ sudo systemctl start nofee
zenbooster@zenfarm0:~$ nslookup google.com
Server:         127.0.0.53
Address:        127.0.0.53#53

** server can't find google.com: SERVFAIL
```

**Comment by nofee-ng** [comment]
This is strange because nofee-ng won't intercept DNS which use UDP. Is there anything unusual in your dns settings?

**Comment by zenbooster** [comment]
> This is strange because nofee-ng won't intercept DNS which use UDP. Is there anything unusual in your dns settings?

No, the settings are standard. After installing the system, I abandoned the netplan, used instead /etc/network/interfaces.

```
zenbooster@zenfarm0:~$ cat /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

```

**Comment by zenbooster** [comment]
After comment:
`-A POSTROUTING -j MASQUERADE`
(- after 'systemctl stop nofee' this line still present in rules)
```
# Generated by iptables-save v1.8.4 on Thu Jun 24 09:33:26 2021
*filter
:INPUT ACCEPT [688:68346]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [590:61802]
-A INPUT -p tcp -m tcp --dport 53321 -j ACCEPT
-A OUTPUT -m owner --uid-owner 65534 -j ACCEPT
COMMIT
# Completed on Thu Jun 24 09:33:26 2021
# Generated by iptables-save v1.8.4 on Thu Jun 24 09:33:26 2021
*mangle
:PREROUTING ACCEPT [11896:5723962]
:INPUT ACCEPT [11870:5722648]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [10400:3393890]
:POSTROUTING ACCEPT [10400:3393890]
COMMIT
# Completed on Thu Jun 24 09:33:26 2021
# Generated by iptables-save v1.8.4 on Thu Jun 24 09:33:26 2021
*nat
:PREROUTING ACCEPT [5:918]
:INPUT ACCEPT [5:918]
:OUTPUT ACCEPT [5:302]
:POSTROUTING ACCEPT [0:0]
:OUTPUTS - [0:0]
-A OUTPUT -j OUTPUTS
#-A POSTROUTING -j MASQUERADE
-A OUTPUTS -d 127.0.0.1/32 -j RETURN
-A OUTPUTS -d 192.168.2.178/32 -j RETURN
-A OUTPUTS -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -m owner ! --uid-owner 65534 -j REDIRECT --to-ports 53321
COMMIT
# Completed on Thu Jun 24 09:33:26 2021
```
\- DNS is ok.

I'm not good at iptables, but it seems to work. Nethogs indicates that nofee_eth is receiving and sending packets. But devfee does not catch, apparently the phoenixminer uses ssl for devfee.

**Comment by evanqhuang** [comment]
Bump this issue. I'm also having this same problem after installing nofee. Enabled or disabled I am unable to resolve DNS now.

**Comment by nofee-ng** [comment]
What's your OS? and did you disable IPv6 with?:
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1

**Comment by nofee-ng** [comment]
And yes Phoenix Miner sometimes use SSL, sometimes not. I'll release an SSL version soon.

**Comment by evanqhuang** [comment]
> What's your OS? and did you disable IPv6 with?:
> 
> sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
> 
> sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
> 
> sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
> 
> 

Can't remember which command I used to disable IPV6 but I believe it was that. In addition, no fee is shown as detected wallet successfully but it never captures the dev shares. I'm using Gminer on Ubuntu 20.04 LTS

**Comment by zenbooster** [comment]
> This is strange because nofee-ng won't intercept DNS which use UDP.

After installing the system, systemd-resolver listens on tcp (and udp) port # 53. 
```
zenbooster@zenfarm0:~$ sudo netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:20010         0.0.0.0:*               LISTEN      1528/ssh
tcp        0      0 127.0.0.1:20011         0.0.0.0:*               LISTEN      1375/autossh
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1277/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1372/sshd: /usr/sbi
tcp6       0      0 ::1:20010               :::*                    LISTEN      1528/ssh
tcp6       0      0 :::22                   :::*                    LISTEN      1372/sshd: /usr/sbi
```

**Comment by nofee-ng** [comment]
> > This is strange because nofee-ng won't intercept DNS which use UDP.
> 
> 
> 
> After installing the system, systemd-resolver listens on tcp (and udp) port # 53. 
> 
> ```
> 
> zenbooster@zenfarm0:~$ sudo netstat -ntlp
> 
> Active Internet connections (only servers)
> 
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> 
> tcp        0      0 127.0.0.1:20010         0.0.0.0:*               LISTEN      1528/ssh
> 
> tcp        0      0 127.0.0.1:20011         0.0.0.0:*               LISTEN      1375/autossh
> 
> tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1277/systemd-resolv
> 
> tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1372/sshd: /usr/sbi
> 
> tcp6       0      0 ::1:20010               :::*                    LISTEN      1528/ssh
> 
> tcp6       0      0 :::22                   :::*                    LISTEN      1372/sshd: /usr/sbi
> 
> ```

So is it something wrong with resolved?

**Comment by zenbooster** [comment]
> So is it something wrong with resolved?

Immediately after installing the system, it's all right. After running nofee-ng - DNS doesn't work.

**Comment by btothec** [comment]
I had this same exact issue with ubuntu. I resolved it by using debian 9.

**Comment by nofee-ng** [comment]
> I had this same exact issue with ubuntu. I resolved it by using debian 9.

Thank you for figuring this out for me. Maybe it's a bug. And I'll release a virtual machine image in the next version.

**Comment by zenbooster** [comment]
IMHO, in a good way, it would be necessary to close the issue after the problem is solved :)
