### ISSUE TITLE
what version of miner  Nofee work ?

### ISSUE THREAD

**Issue by Jonasuke59** [nofee-ng/nofee-ng#29]
Hello, thank you for your help.

What version of miner Nofee work perfect?

Because i use TeamRedMiner 0.8.5 & PhoenixMiner 5.7b (Crash with Nofee).
I have AMD card only

Best Regards

**Comment by nofee-ng** [comment]
Please check supported miners here: https://github.com/nofee-ng/nofee-ng/blob/master/nofee_eth/README.md

**Comment by Jonasuke59** [comment]
ok dont work for me
