### ISSUE TITLE
Bringing binary blobs into my farms?

### ISSUE THREAD

**Issue by mrheat** [nofee-ng/nofee-ng#3]
Without providing source, it seems a little weird to deploy this into any mining farm.
Sorry with out any reputation via your account or denying a simple question about the inner details
like "how is this working" answer: "Sorry, I don't want to discuss the mechanism. Just use it."

i guess it smells a bit strange to my taste with this dont you think?
im always to have for the right arguments, so feel free to change my mind ;)

**Comment by nofee-ng** [comment]
Our main product is the diskless mining solution for farms. The nofee-ng is just a free additional gift to our clients.
