### ISSUE TITLE
Multiple machines break it, or possibly just hiveos.

### ISSUE THREAD

**Issue by btothec** [nofee-ng/nofee-ng#33]
So I have the standalone version of this setup. I have one rig running for days fine, it is running on simplemining (SMOS). I just pointed another rig to it that is running on HiveOS. When this rig is pointed to the router, all of the traffic goes to the redirect wallet (nodev wallet specified in nofee.txt).

I have tried to figure out exactly what is going on but I am at a loss. I am using pfsense as the main network router, and have specified the nodevfee soft router in pfsense as a backup gateway. The rigs are setup on the client side as dhcp and inside pfsense as static so I can easily chance the gateway. 

I am running the soft router on a vm running debian 9.

**Comment by nofee-ng** [comment]
What is your rig name?

**Comment by btothec** [comment]
Sorry -- I had pointed a rig to the test machine from outside the local network. I tested it with a local rig on hive and I think it is fine. "AustinRig" is the rig name however.
