### ISSUE TITLE
大佬你好。T-rex 和 teamredminer 可以支持吗？ 

### ISSUE THREAD

**Issue by lootwealth** [nofee-ng/nofee-ng#9]

**Comment by nofee-ng** [comment]
我先测试一下，稍后给您答复

**Comment by gtirsmiley** [comment]
Any update? looking for trex support

**Comment by nofee-ng** [comment]
teamredminer is supported by nofee-ng, the refunded devfee can be found at nanopool: https://eth.nanopool.org/
I don't have a Nvidia gpu right now, so t-rex is not tested.

**Comment by nofee-ng** [comment]
You can check whether teamredminer is supported by systemctl status nofee: If DevFee is found, a line `DevFee found` will show up in `systemctl status nofee`. But remember **NOT ALL** DevFee found will become valid shares on the pool

**Comment by jd1900** [comment]
I don't see anything with t-rex.

It is not supported?
Maybe an older version is?

**Comment by nofee-ng** [comment]
I didn't test with t-rex because I don't have an Nvidia card. It may be not supported if it use an SSL connection right now. But I will release a version which supports SSL stratum soon.

**Comment by jd1900** [comment]
That's great news!
